- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

# Just a test to understand the src parameter.  
# Test.md is in the ansible file folder
- name: Copy test file to remote server
  copy:
    src: test.md
    dest: /home/ubuntu

- name: Creates directory 
  file:
    path: /home/ubuntu/backend
    state: directory

# - name: "move files to server"
#   become: true
#   copy:
#     src: /root/project/backend/dist
#     dest: /home/ubuntu/backend
#     remote_src: yes
#     mode: '0777'

- name: "Copy backend tar.gz file and unzip it"
  become: yes
  unarchive:
    src: backend.tar.gz
    dest: /home/ubuntu

# pm2 will automatically restart your application if it crashes
# pm2 will keep a log of your unhandled exceptions /home/<user>/.pm2/logs/app-err.log.
# learn more: https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps
- name: Start backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls

- name: Install Promethesus Node Exporter
  become: true
  shell: |
    sudo useradd --no-create-home node_exporter
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: Copy node-exporter.service file to remote server
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: Configure systemd for Prometheus
  become: true
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable node-exporter
    sudo systemctl start node-exporter
    sudo systemctl status node-exporter

# - name: start pm2 for dist/main.js
#   shell: pm2 start main.js
#   args:
#     chdir: /home/ubuntu/backend/dist