- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

# Just a test to understand the src parameter.  
# Test.md is in the ansible file folder
- name: Copy test file to remote server
  copy:
    src: test.md
    dest: /home/ubuntu

- name: Creates directory 
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "move files to server"
  become: true
  copy:
    src: /root/project/backend/dist
    dest: /home/ubuntu/backend
    remote_src: yes
    mode: '0777'

# - name: "Copy backend tar.gz file and unzip it"
#   become: yes
#   unarchive:
#     src: /root/project/backend.tar.gz #next step is to try this.  I removed the extra backend.
#     dest: /home/ubuntu
#     # copy: yes
#     remote_src: yes
    

# - name: "Fix critical dependencies"
#   become: true
#   command: npm audit fix & npm audit fix --audit-level=critical --force
#   args:
#     chdir: /home/ubuntu/backend

# - name: "move files to server"
#   become: true
#   copy:
#     src: /root/project/backend/dist
#     dest: /home/ubuntu/backend
#     remote_src: yes
#     mode: '0777'

# - name: "deploy backend app to new location"
#   become: true
#   copy:
#     src:  /root/project/backend/.env
#     dest: /home/ubuntu/backend/

# - name: Building backend service
#   shell: |
#     cd /home/ubuntu/backend
#     npm run build
#     npm run prestart:prod

# - name: "build application"
#   become: true
#   command: npm run build 
#   args:
#     chdir: /home/ubuntu/backend

# - name: "Run migrations"
#   become: true
#   command: npm run migrations
#   args:    
#     chdir: /home/ubuntu/backend

# pm2 will automatically restart your application if it crashes
# pm2 will keep a log of your unhandled exceptions /home/<user>/.pm2/logs/app-err.log.
# learn more: https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps
- name: Start backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls

- name: start pm2 for dist/main.js
  become: no
  shell: pm2 start main.js
  args:
    chdir: /home/ubuntu/backend/dist