- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Creates directory 
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy backend tar.gz file and unzip it"
  become: yes
  unarchive:
    src: backend.tar.gz
    dest: /home/ubuntu

# pm2 will automatically restart your application if it crashes
# pm2 will keep a log of your unhandled exceptions /home/<user>/.pm2/logs/app-err.log.
# learn more: https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps
- name: Start backend
  become: true
  shell: |
    cd /home/ubuntu/dist
    sudo pm2 start npm --name backend -- start
    sudo pm2 ls
    sudo pm2 logs

  environment:
    Environment:
      ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"