- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install prometheus server."
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move prometheus server binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: '0777'

- name: "add prometheus server configuration."
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: "install prometheus Alert Manager."
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.23.0/alertmanager-0.23.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move prometheus server binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: '0777'

- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes