# Task definition for alert manager
# Alert Manager Configuration
# Resource: https://codewizardly.com/prometheus-on-aws-ec2-part4/
# ----------------------------
- name: Creates Prometheus directory 
  file:
    path: /var/lib/alertmanager
    state: directory

- name: "install prometheus Alert Manager."
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.23.0/alertmanager-0.23.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move prometheus AlertManager binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.23.0.linux-amd64/alertmanager
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0777'

- name: "move prometheus AlertManager binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.23.0.linux-amd64/amtool
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0777'

- name: "enable prometheus alert manager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes