# Task definition for alert manager
# Alert Manager Configuration
# Resource: https://codewizardly.com/prometheus-on-aws-ec2-part4/
# ----------------------------
- name: Creates Prometheus directory 
  file:
    path: /var/lib/alertmanager
    state: directory

- name: "install prometheus Alert Manager."
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.23.0/alertmanager-0.23.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move prometheus AlertManager binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.23.0.linux-amd64/alertmanager
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0777'

- name: "move prometheus Amtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.23.0.linux-amd64/amtool
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0777'

- name: "Add alert manager configuration to prometheus folder."
  become: true
  copy:
    src: alertmanager.yml
    dest: /etc/prometheus/

- name: "Add slack configuration configuration to prometheus folder."
  become: true
  copy:
    src: slack_configuration.yml
    dest: /etc/prometheus/

- name: "Add prometheus unit file to systemd folder."
  become: true
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/

- name: "enable prometheus alert manager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes

- name: "Check status on alertmanager"
  shell: |
    sudo systemctl status alertmanager
    # sudo systemctl restart prometheus