Description: >
  UdaPeople Prometheus server stack.

Resources:
  PrometheusSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow port 22 and prometheus ports
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22 # Admin SSH
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100 # Port for prometheus server
          ToPort: 9100
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093 # Port for prometheus AlertManager service
          ToPort: 9093
          CidrIp: 0.0.0.0/0

  PrometheusEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SecurityGroups:
        - Ref: PrometheusSecurityGroup
      KeyName: udacity-project3-key # If you use another key pair name, you should change this value to match.
      # If this ami id is not available for you, you can find another (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html)
      # Ubuntu 18 or higher works fine
      ImageId: ami-09e67e426f25ce0d7 #ami-0747bdcabd34c712a #ami-00ddb0e5626798373 
      Tags:
        - Key: Name
          Value: Prometheus Server

  AssociatePrometheusElasticIP:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: eipalloc-0d49b433d438bde57
      InstanceId: !Ref PrometheusEC2Instance
      
Outputs:
  PrometheusURL:
    Description: The backend DNS (host name)
    Value: !Join ["", ["http://", !GetAtt PrometheusEC2Instance.PublicDnsName,":9090"]]
    Export:
      Name: PrometheusMonitorURL