# More info: https://classroom.udacity.com/nanodegrees/nd9991/parts/49ac1f4a-6345-4b9f-85dc-6db637ba8c22/modules/c4ef4afe-70f0-48a5-b671-693114a87a1d/lessons/f7413591-315a-45e6-90d9-34bc67e2388c/concepts/b2df7e84-43f4-40a0-acf0-88e7c088d97b

Parameters:
# New Bucket name
MyBucketName:
  Description: Existing Bucket name
  Type: String
Resources:
WebsiteBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Sub "${MyBucketName}"
    AccessControl: PublicRead
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: error.html
WebsiteBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref 'WebsiteBucket'
    PolicyDocument:
      Statement:
      - Sid: PublicReadForGetBucketObjects
        Effect: Allow
        Principal: '*'
        Action: s3:GetObject
        Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]