global:
  resolve_timeout: 1m
  slack_api_url: test_slack_webhook
route:
  receiver: slack-email-alert-notice
  group_by:
  - alertname
  - datacenter
  - app
receivers:
- name: slack-email-alert-notice
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: "[{{ .Status | toUpper }}{{ if eq .Status \"firing\" }}:{{ .Alerts.Firing\
      \ | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job\
      \ }}\n{{- if gt (len .CommonLabels) (len .GroupLabels) -}}\n  {{\" \"}}(\n \
      \ {{- with .CommonLabels.Remove .GroupLabels.Names }}\n    {{- range $index,\
      \ $label := .SortedPairs -}}\n      {{ if $index }}, {{ end }}\n      {{- $label.Name\
      \ }}=\"{{ $label.Value -}}\"\n    {{- end }}\n  {{- end -}}\n  )\n{{- end }}\n\
      text: >-\n{{ range .Alerts -}}\n*Alert:* {{ .Annotations.title }}{{ if .Labels.severity\
      \ }} - `{{ .Labels.severity }}`{{ end }}\n\n*Description:* {{ .Annotations.description\
      \ }}\n\n*Details:*\n  {{ range .Labels.SortedPairs }} \u2022 *{{ .Name }}:*\
      \ `{{ .Value }}`\n  {{ end }}\n{{ end }}"
  email_configs:
  - to: test@test.com
    from: test@test.com
    smarthost: smtp.gmail.com:587
    auth_username: test@test.com
    auth_identity: test@test.com
    auth_password: test_password
    send_resolved: true
